deploy-stack-09 deploy-stack-10 deploy-stack-11 deploy-stack-12 deploy-stack-13 deploy-stack-14: deploy-stack-%:
	./commands.sh deploy-stack $*

delete-stack-09 delete-stack-10 delete-stack-11 delete-stack-12 delete-stack-13 delete-stack-14: delete-stack-%:
	./commands.sh delete-stack $*

get-ec2-ip-09 get-ec2-ip-10 get-ec2-ip-11 get-ec2-ip-12 get-ec2-ip-13 get-ec2-ip-14: get-ec2-ip-%:
	./commands.sh get-ec2-ip $*

deploy-build-stack-01: deploy-build-stack-%:
	./commands.sh deploy-build-stack $*

delete-build-stack:
	./commands.sh delete-build-stack

get-deployment-bucket:
	./commands.sh get-deployment-bucket

app-package:
	./commands.sh app-package

app-upload: app-package
	./commands.sh app-upload
