.SILENT: deploy-stack-05 deploy-stack-06 deploy-stack-07 deploy-stack-08 deploy-stack-09 delete-stack get-ec2-ip

deploy-stack-05 deploy-stack-06 deploy-stack-07 deploy-stack-08 deploy-stack-09 : deploy-stack-%:
	./commands.sh deploy-stack $*

delete-stack:
	./commands.sh delete-stack

get-ec2-ip:
	./commands.sh get-ec2-ip
